### ISSUE TITLE
More SEO options

### ISSUE THREAD

**Issue by Egliote** [paperbits/paperbits-demo#157]
Paperbits SEO now is pretty basic. It would be awesome to have more sophisticated options, for example, parametrizate some data in SEO metadescription and title (in my case it would be country name and price). Also it would be great to have different SEO for some pages.

**Comment by azaslonov** [comment]
That is true, it is very basic currently. However, we have advanced SEO module in development (I believe it will be ready by end of August).

Also, even now you can enable fields for social sharing images and JSON-LD even now: just put `"enableSeo": true` into `config.design.json`. When you publish the website, those structures will be injected into the page.

**Comment by azaslonov** [comment]
I have created a separate feature request (#158) to give it visibility. So, I'm closing this one for now.
