### ISSUE TITLE
Not able to edit text in the editor - after clicking on edit text the pointer is not going to the text

### ISSUE THREAD

**Issue by SSanjeevi** [paperbits/paperbits-demo#207]
**Describe the bug**
Not able to edit text in the editor - after clicking on edit text the pointer is not going to the text

**To Reproduce**
1. Go to any text in page
2. Click on edit text button
3. now the focus is not going to text inside that section, or its not allowing to click on the text for editing, when we click on text its again asking for edit text button click - and its repeating, this i can see in new version.

**Expected behavior**
On click on edit text it should focus the text inside the section for editing it or it should edit on click of content.

**Screenshots**
![image](https://user-images.githubusercontent.com/24915474/202879376-ccebf70a-029b-4813-a28f-39de9dc0e38e.png)
![image](https://user-images.githubusercontent.com/24915474/202879387-7bbb3168-6048-42a9-9484-fb284fea3bac.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser edge
 - Version "version": "0.1.526",

**Additional context**
I haven't faced this issue in older version where we had edit as button option, now it contains edit text in button option.

**Comment by azaslonov** [comment]
Hi Sanjeevi, thanks, we're working on it right now. We'll publish the fixed libraries soon.

**Comment by azaslonov** [comment]
Fixed in version 0.1.533.
