### ISSUE TITLE
Running paperbits on arbitrary subpath

### ISSUE THREAD

**Issue by joshua-mng** [paperbits/paperbits-demo#211]
Im trying to use this wonderful library in my project. Basically my app is running on following url.

https://mydomain.com/

I want to do following 2 things

1. Run published website on sub path, like https://mydomain.com/mysite1
2. Run designer on sub path, like https://mydomain.com/sites/mysite1/designer

I replaced default PermalinkResolver and MediaPermalinkResolver to prepend /mysite1 in front of urls during publishing so now published site works partially on sub path /mysite1

I'm serving designer assets on https://mydomain.com/sites/mysite1/designer which works partially

I can replace, permalink resolver, blob storage, object storage to use my custom backend.

But problem is:

- Event some components are replaced to handle the extra subpath, still designer is unable to load some data, like block-snippets.json, etc because those are hard coded in paperbits/constants.ts file, so what Im doing is replacing all occurences of those constant url path strings in paperbits.js file dynamically.
- I configured /data/demo.json path to be relative to the subpath correctly, and designer loads, but it says page not found error on initial load. I suspect something has to do with the path, like /mysite1/wiki/getting-started is not being resolved to /wik/getting-started
- When I click on individual pages in the pages widget, page are shown, but their url is relative to root path, like /wiki/getting-started instead of /mysite1/wiki/getting-started

So the question is what is the best way to achieve this? (Running published website and designer or arbitrary dynamic subpath)

Thank you

**Comment by msrshahrukh100** [comment]
This is very similar to my issue #208

**Comment by azaslonov** [comment]
@joshua-mng, for the first issue, as @msrshahrukh100 mentioned, we'll expose respective settings to override hardcoded values this week. For the rest two issues, let me get back to you (also this week).

**Comment by joshua-mng** [comment]
Thank you for your quick response. And this is indeed very similar to issue #208, but there is a subtle difference.

In my case, subpath to run the website and designer is actually not a fixed sub path known at build time rather than using webpack's output.publicPath which is a path known at build time.

What would be so helpful in my case is if I can inject these subpath information to paperbits in the index.html or page.html file via attributes. Like, 

<html data-base-path="/mysite1">
   ....

reason for this is that, I can compute the subpath at runtime.

Any other solution would be appreciated, thank you.

**Comment by azaslonov** [comment]
Hi @joshua-mng, wow, you've got pretty deep into the code, amazing! :). I remember we had a question like this and we suggested a router below. It's a bit outdated, but should still work. Let me know if you still have an issue.

Also, I have exposed these in some settings (see [design.config.json](https://github.com/paperbits/paperbits-demo/blob/master/src/config.design.json#L22-L26)) version 0.1.534. Let me check the rest resources you suggested a bit later.


Here's the router:
```
import { EventManager } from "@paperbits/common/events";
import { Router, RouterEvents, Route, RouteGuard } from "@paperbits/common/routing";

export class RelativePathRouter implements Router {
    public currentRoute: Route;
    public notifyListeners: boolean;
    private readonly basePath: string;

    constructor(
        private readonly eventManager: EventManager,
        private readonly routeGuards: RouteGuard[],
    ) {
        // setting up...
        this.notifyListeners = true;

        const segments = window.location.pathname.split("/");
        this.basePath = "/" + segments[1] + "/" + segments[2];

        this.currentRoute = this.getRouteFromLocation();
    }

    public getRouteFromLocation(): Route {
        const path = "/" + location.pathname.substr(this.basePath.length + 1);
        const hash = location.hash.startsWith("#") ? location.hash.slice(1) : location.hash;
        const url = location.pathname + hash;

        const route: Route = {
            url: url,
            path: path,
            metadata: {},
            hash: hash,
            previous: null
        };

        return route;
    }

    public addRouteChangeListener(eventHandler: (args?: any) => void): void {
        this.eventManager.addEventListener(RouterEvents.onRouteChange, eventHandler);
    }

    public removeRouteChangeListener(eventHandler: (args?: any) => void): void {
        this.eventManager.removeEventListener(RouterEvents.onRouteChange, eventHandler);
    }

    /**
     * Navigates to specified URL.
     * @param url Absolute or relative path, i.e. https://paperbits.io or /about
     * @param title Destination title
     * @param metadata Associated metadata
     */
    public async navigateTo(url: string, title: string = null, metadata: Object = {}): Promise<void> {
        if (!url) {
            return;
        }

        const isFullUrl = url && (url.startsWith("http://") || url.startsWith("https://"));
        const isLocalUrl = url.startsWith(location.origin);

        if (isFullUrl && !isLocalUrl) {
            window.open(url, "_blank"); // navigating external link
            return;
        }

        url = isFullUrl
            ? url.substring(location.origin.length)
            : url;

        const parts = url.split("#");

        const route: Route = {
            url: this.appendBasePath(url),
            path: parts.length > 1 ? parts[0] || location.pathname : parts[0],
            title: title,
            metadata: metadata,
            hash: parts.length > 1 ? parts[1] : "",
            previous: this.currentRoute
        };

        const canActivate = await this.canActivate(route);

        if (canActivate) {
            this.currentRoute = route;

            if (this.notifyListeners) {
                this.eventManager.dispatchEvent(RouterEvents.onRouteChange, route);
            }
        }
    }

    protected async canActivate(route: Route): Promise<boolean> {
        for (const routeGuard of this.routeGuards) {
            try {
                const canActivate = await routeGuard.canActivate(route);

                if (!canActivate) {
                    return false;
                }
            }
            catch (error) {
                throw new Error(`Unable to invoke route a guard: ${error}`);
                return false;
            }
        }

        return true;
    }

    public getCurrentUrl(): string {
        let permalink = this.currentRoute.path;

        const hash = this.getHash();

        if (this.currentRoute.hash) {
            permalink += "#" + hash;
        }

        return permalink;
    }

    public getCurrentUrlMetadata(): Object {
        return this.currentRoute.metadata;
    }

    public getPath(): string {
        return this.currentRoute.path;
    }

    public getHash(): string {
        return this.currentRoute.hash;
    }

    public getCurrentRoute(): Route {
        return this.currentRoute;
    }

    private appendBasePath(url: string): string {
        return url.startsWith("/") ? this.basePath + url : this.basePath + "/" + url;
    }

    public addHistoryUpdateListener(eventHandler: (args?: any) => void): void {
        // Not supported
    }

    public removeHistoryUpdateListener(eventHandler: (args?: any) => void): void {
        // Not supported
    }

    public updateHistory(url: string, title?: string): void {
        // Not supported
    }
}
```

**Comment by azaslonov** [comment]
Great to hear that! Agree on magic strings, we'll get rid of them.

Closing the issue since questions resolved. Please feel free to reopen shall you need further assistance.
