### ISSUE TITLE
Running paperbits without publishing

### ISSUE THREAD

**Issue by joshua-mng** [paperbits/paperbits-demo#212]
Is it possible to run paperbits based website without first publishing to static assets?

Like paperbit will render components at runtime in the browser (like how designer is doing it, but without designer features).

If possible, then how should I do that, thank you.

**Comment by azaslonov** [comment]
Hi @joshua-mng, are you talking about something like a "preview" mode, like with this button on demo.papaerbits.io:
![image](https://user-images.githubusercontent.com/2320302/205463374-3fc9c731-d261-4dd7-bb35-13c0561ba5fd.png)

If yes, there is no out-of-the-box support for that, but looking at the "preview" mode implementation you can get the idea how to achieve the same (just look for `ViewManagerMode.preview` constant usage). This probably means that in your production websites, you'll have to dynamically load the source JSON and render everything in browser making it a full-blown SPA. The one problem with SPA, however, is that search engines won't be able to crawl and hence index such websites.

**Comment by joshua-mng** [comment]
Yeah, Something like that preview mode. If I can combine it with server side rendering, then SEO will be no problem. Could be separate paperbits-spa projects. Thank you very much.

**Comment by azaslonov** [comment]
@joshua-mng, closing the issue, since the question answered. Please feel free to re-open shall you need further assistance.
