### ISSUE TITLE
Table number of rows/cols editor does not work

### ISSUE THREAD

**Issue by JMach1** [paperbits/paperbits-demo#215]
Changes in Table editor does not propagate and are not persistent (notice that after I changed num of cols/rows not even the save button gets enabled).

component: **paperbits-core\src\table**

Related issue (same component): https://github.com/paperbits/paperbits-demo/issues/216

![paperbits table bug](https://user-images.githubusercontent.com/92859870/205346771-a7737a6e-bf5f-4e83-a3ff-f70887dff2ac.gif)

**Comment by JMach1** [comment]
Related issue (same component): https://github.com/paperbits/paperbits-demo/issues/new?assignees=&labels=accessibility%2C+bug&template=bug_report_accessibility.md

**Comment by azaslonov** [comment]
Fixed in version 0.1.536.
