### ISSUE TITLE
Missing block class in divider.

### ISSUE THREAD

**Issue by javierbo1989** [paperbits/paperbits-demo#220]
Previously the dividing line had a "block" class that has been removed in new versions. This has affected the display of the developer portal for some customers.

Now:
![image](https://user-images.githubusercontent.com/88548172/206809571-20dffad2-1296-47ed-a572-9559ea15332c.png)

Before:
![image](https://user-images.githubusercontent.com/88548172/206809518-d891e7b9-92fd-4ea8-8570-324c75f80525.png)

**Comment by azaslonov** [comment]
Fixed in version 0.1.536.
