### ISSUE TITLE
Issues with prosemirrorHtmlEditor breaks build locally, entirely on Vercel

### ISSUE THREAD

**Issue by skybird-dev** [paperbits/paperbits-demo#221]
**Describe the bug**
multiple issues with prosemirror

**To Reproduce**
Uncommenting firebase modules and entering all firebase data in config.design.json & config.publish.json 

**Expected behavior**
loading website for editing

**Screenshots**
Upon Compiling, errors show up in the browser:
![Screen Shot 2022-12-10 at 6 28 28 AM](https://user-images.githubusercontent.com/117532029/206860410-8e5bea70-108c-425f-9921-73e1063aa92f.png)

But you can click the X to ignore them.
![Screen Shot 2022-12-10 at 6 28 40 AM](https://user-images.githubusercontent.com/117532029/206860413-dbd73f22-40d5-4095-9818-f423fafe9ad6.png)

__________________________
Compiled with problems gitpod.io with visual studio

ERROR in ./node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts (/workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts) 103:39-46

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(103,40)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in ./node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts (/workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts) 257:29-36

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(257,30)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in ./node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts (/workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts) 257:82-89

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(257,83)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in ./node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts (/workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts) 276:127-134

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(276,128)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in ./node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts (/workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts) 349:44-51

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(349,45)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in ./node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts (/workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts) 350:63-70

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(350,64)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in ./node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts (/workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts) 402:55-62

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(402,56)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in ./node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts (/workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts) 438:55-62

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(438,56)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in ./node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts (/workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts) 515:12-47

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(515,13)
      TS2322: Type 'boolean' is not assignable to type 'string'.

ERROR in ./node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts (/workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts) 534:43-48

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(534,44)
      TS2740: Type 'Element' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 116 more.

ERROR in ./node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts (/workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts) 551:8-43

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(551,9)
      TS2322: Type 'boolean' is not assignable to type 'string'.

ERROR in ./node_modules/@paperbits/prosemirror/keymap.ts (/workspace/skybird.app/node_modules/@paperbits/prosemirror/keymap.ts) 87:20-27

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/keymap.ts(87,21)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts 103:39-46

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(103,40)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts 257:29-36

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(257,30)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts 257:82-89

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(257,83)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts 276:127-134

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(276,128)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts 349:44-51

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(349,45)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts 350:63-70

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(350,64)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts 402:55-62

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(402,56)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts 438:55-62

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(438,56)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts 515:12-47

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(515,13)
      TS2322: Type 'boolean' is not assignable to type 'string'.

ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts 534:43-48

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(534,44)
      TS2740: Type 'Element' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 116 more.

ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts 551:8-43

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/prosemirrorHtmlEditor.ts(551,9)
      TS2322: Type 'boolean' is not assignable to type 'string'.

ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/keymap.ts 87:20-27

[tsl] ERROR in /workspace/skybird.app/node_modules/@paperbits/prosemirror/keymap.ts(87,21)
      TS2339: Property '$cursor' does not exist on type 'Selection'.

_________________________\

With Vercel, it will not even do that much:
![Screen Shot 2022-12-10 at 6 29 11 AM](https://user-images.githubusercontent.com/117532029/206860466-be15f49a-5e2c-45bd-baa3-f2cd5090802a.png)
![Screen Shot 2022-12-10 at 6 33 01 AM](https://user-images.githubusercontent.com/117532029/206860543-0726457a-0783-4fb9-b621-7687974843d2.png)
![Screen Shot 2022-12-10 at 6 33 07 AM](https://user-images.githubusercontent.com/117532029/206860548-ceb95bae-92c1-4d06-a1df-ae9425a531f7.png)
![Screen Shot 2022-12-10 at 6 33 11 AM](https://user-images.githubusercontent.com/117532029/206860551-db96e839-e30a-45e2-916c-1a46aa8a9c56.png)
![Screen Shot 2022-12-10 at 6 33 17 AM](https://user-images.githubusercontent.com/117532029/206860558-29949afd-085d-450d-aa63-65cc272d54b7.png)
![Screen Shot 2022-12-10 at 6 33 22 AM](https://user-images.githubusercontent.com/117532029/206860561-e6228dbf-b481-415a-a1fd-7ca1f8d9d39e.png)
![Screen Shot 2022-12-10 at 6 33 27 AM](https://user-images.githubusercontent.com/117532029/206860568-c885d359-5173-4070-a17b-dd4614f08fe7.png)
![Screen Shot 2022-12-10 at 6 33 31 AM](https://user-images.githubusercontent.com/117532029/206860569-e437e888-dfb0-4d26-9cfe-91a7603321a9.png)
![Screen Shot 2022-12-10 at 6 33 38 AM](https://user-images.githubusercontent.com/117532029/206860573-6fcf5d2b-55d3-448a-941a-a048ce7cf223.png)

**Comment by azaslonov** [comment]
Fixed in version 0.1.536.
