### ISSUE TITLE
Property 'flow' does not exist

### ISSUE THREAD

**Issue by capoia** [paperbits/paperbits-demo#226]
**Describe the bug**
When trying to use vue in the demo, it returns two errors about properties that do not exist.

**To Reproduce**
1 - Clone the demo
2 - Follow the instructions in this readme (https://github.com/paperbits/examples/tree/master/ui-frameworks/vue/components)
3 - npm start

**Expected behavior**
The demo running successfully and the component in vue

**Screenshots**
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/21159928/219122531-312f482c-d115-4994-8e9c-48308d1eb931.png">
![image](https://user-images.githubusercontent.com/21159928/219122730-66f80eb0-1cf6-455e-b8e1-bd784d9161a1.png)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser: Firefox
 - Version: 109.0.1

**Additional context**
When importing 'ClickCounterPublishnModule' as stated in the readme, it returns an error:
'"../components/click-counter/clickCounter.publish.module"' has no exported member named 'ClickCounterPublishnModule'. Did you mean 'ClickCounterModule'?

Changing to the suggested name this error disappears, I only mention it because it may have something to do with it.

**Comment by azaslonov** [comment]
Hi @capoia, yup, this is known issue, we're working on it. Should be fixed by 2/20.

**Comment by azaslonov** [comment]
@capoia, I have updated Vue widget example. Also, to make it faster you can just grab [az/vue](https://github.com/paperbits/paperbits-demo/tree/az/vue) branch and take it from there. Support for Vue 3 and respective documentation is coming soon.
