### ISSUE TITLE
vedios are unable to upload using both link and uploads,button appearance is not been changed except default,gradient is unable to change except blue color

### ISSUE THREAD

**Issue by chita-creator99** [paperbits/paperbits-demo#51]
I tried uploading vedios using both uploads and link through cdn option which was not been taken ,It showed as invalid source .
The button appearance is taken as default and no more option in button appearance is been shown.
Also gradient color was unable to change using style guide.

**Comment by azaslonov** [comment]
Hi there,

**Video player**
As we discussed through the chat, you were trying to assign Youtube URL to Video Player widget, which supports only `video/mp4`, `video/webm` and `video/ogg` formats. There is a separate Youtube Player widget.

**Button appearance**
Component variants (including buttons) can be added in the Style Guide:
![image](https://user-images.githubusercontent.com/2320302/71744566-8a271300-2e1c-11ea-9858-64567130e6c2.png)

**Gradients**
Gradient editor is not ready yet, it should be out in 4-5 weeks.

Hope that helps.
