### ISSUE TITLE
Support for real time preview

### ISSUE THREAD

**Issue by pouyamiralayi** [paperbits/paperbits-demo#56]
Awesome project, great work! When you are in the editor, you can not interact with the content as an end user. It would be nice to have an on demand preview of the content while we are editing; this would allow us to deliver a more precise UX as the final result without waiting for the ``publish`` process every time.

For the solution, one can say now that we have templates, we may use custom htmlParser() for cases such as ``vue`` or ``react``; That being said we can also have a preview app as well; for instance we have a preview app written in ``vue`` that accepts and works with our template & viewModels, just like an actual app.

For the alternatives to this, i guess we can automate the ``publish`` process to have a live preview, but that's not the case; we can not use this process when we are providing paperbits as a service.

![image](https://user-images.githubusercontent.com/53266765/72787461-35b9cb00-3c45-11ea-974b-64c32e95288b.png)

cheers!

**Comment by azaslonov** [comment]
Hi @pouyamiralayi, thank you for feedback and suggestion!
You're right, real time preview should be a nice addition. We'll add it very soon.
