### ISSUE TITLE
Add widget implementation examples in React.

### ISSUE THREAD

**Issue by azaslonov** [paperbits/paperbits-demo#59]

**Comment by guideveloper** [comment]
Hi, Do you have an idea as to when the react based widgets will be available?

**Comment by azaslonov** [comment]
Hi @guideveloper, we'll try to make it in the next couple of weeks.

**Comment by guideveloper** [comment]
Awesome thanks

**Comment by guideveloper** [comment]
@azaslonov Any news on the React widgets?

**Comment by azaslonov** [comment]
Hi Craig, sorry, I know you're waiting for long time already. Will do by end of this week, promise :)

**Comment by guideveloper** [comment]
Cool man nice one.
