### ISSUE TITLE
The section library is not loading

### ISSUE THREAD

**Issue by mtuchkov** [paperbits/paperbits-demo#64]
**Describe the bug**
The section library is not loading

![picturemessage_oowgg3zd qwf](https://user-images.githubusercontent.com/4992379/73646911-44ce4f00-462f-11ea-8c20-606d5caeaf25.png)

**To Reproduce**
1. Add the demo project header with a menu to the library.
2. Reload editor
3. Open section library

**Comment by mtuchkov** [comment]
[production-papersites-blocks-export.txt](https://github.com/paperbits/paperbits-demo/files/4147483/production-papersites-blocks-export.txt)




[production-papersites-1d1d5827-5a0b-fc1c-0560-b39e7cb382d6-export.txt](https://github.com/paperbits/paperbits-demo/files/4147496/production-papersites-1d1d5827-5a0b-fc1c-0560-b39e7cb382d6-export.txt)
[production-papersites-dd0aa696-0695-37d4-0f1e-9fa790f5920c-export.txt](https://github.com/paperbits/paperbits-demo/files/4147497/production-papersites-dd0aa696-0695-37d4-0f1e-9fa790f5920c-export.txt)
[production-papersites-b8cdab31-3275-d91f-4be0-8397b09764b8-export.txt](https://github.com/paperbits/paperbits-demo/files/4147498/production-papersites-b8cdab31-3275-d91f-4be0-8397b09764b8-export.txt)
[production-papersites-440aeacb-e07b-3608-abc0-595ea4393347-export.txt](https://github.com/paperbits/paperbits-demo/files/4147500/production-papersites-440aeacb-e07b-3608-abc0-595ea4393347-export.txt)

**Comment by mtuchkov** [comment]
The sections from the library attached.

**Comment by azaslonov** [comment]
Fixed.
