### ISSUE TITLE
Errors when building demo project

### ISSUE THREAD

**Issue by digital88** [paperbits/paperbits-demo#74]
**Describe the bug**
When running "npm start" I'm getting this errors in console:
ERROR in [at-loader] ./node_modules/@paperbits/common/styles/styleSheet.ts:3:26 
    TS2307: Cannot find module './FontFace'.

ERROR in [at-loader] ./node_modules/@paperbits/common/vue/decorators/component.decorator.ts:1:33 
    TS2307: Cannot find module './ComponentConfig'.

ERROR in [at-loader] ./node_modules/@paperbits/common/vue/decorators/decorators.ts:3:31 
    TS2307: Cannot find module './LifecylceHook'.

**To Reproduce**
1. git clone paperbits-demo project
2. npm install
3. npm start

**Expected behavior**
No errors in console

**Screenshots**
![image](https://user-images.githubusercontent.com/10961828/75688372-71b66600-5cb0-11ea-9b11-bdffd3154cb8.png)

**Desktop:**
 - OS: Linux Ubuntu 17.04
 - Browser Chrome
 - Version 79

**Comment by azaslonov** [comment]
Hi @digital88, thanks for reporting the issue. We'll fix that.

**Comment by azaslonov** [comment]
Hi @digital88, the issue should be gone now. Please give it a try.

**Comment by azaslonov** [comment]
Hi @digital88, the issue has been fixed. Please pull the latest changes.
