### ISSUE TITLE
email editor doesn't work properly

### ISSUE THREAD

**Issue by cutloose** [paperbits/paperbits-demo#76]
**Describe the bug**
no editing control in demo interface
**To Reproduce**
install paperbits demo, select email to edit, try to get edit
expected that I can change text,images, button content after adding

**Comment by azaslonov** [comment]
Hi @cutloose, thank you for reporting the issue. We'll fix that.

**Comment by azaslonov** [comment]
Hi @digital88, the issue has been fixed. Please pull the latest changes.
