### ISSUE TITLE
Suggestion for paperbits homepage regarding styling

### ISSUE THREAD

**Issue by kerryj89** [paperbits/paperbits-demo#97]
I was excited to try and use paperbits to wrap around my existing CSS.  Unfortunately (for me), paperbits seems to be a CSS-in-JS approach.  I think it would be nice if you have a bullet point "CSS-in-JS approach" under "Theme and framework agnostic" on your homepage so users know immediately the approach used to style.  By "Theme and framework agnostic" I was thinking in the context of CSS frameworks and not JS app frameworks.

I hope to try this out again in the future when we can make the jump!

**Comment by azaslonov** [comment]
Hi @kerryj89, thanks for the suggestion, I think you're right, we'll see how we can improve the messaging.
